/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        app: 'var(--background)',
        main: 'var(--foreground)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        success: 'var(--success)',
        danger: 'var(--danger)',
        warning: 'var(--warning)',
        surface: 'var(--surface)',
        'surface-soft': 'var(--surface-soft)',
        'surface-muted': 'var(--surface-muted)',
        'surface-primary': 'var(--surface-primary)',
        'surface-secondary': 'var(--surface-secondary)',
        'surface-elevated': 'var(--surface-elevated)',
        nav: 'var(--nav)',
        'nav-foreground': 'var(--nav-foreground)',
        'tab-inactive': 'var(--tab-inactive)',
        chip: 'var(--chip)',
        'chip-active': 'var(--chip-active)',
        overlay: 'var(--overlay)',
        'accent-gold': 'var(--accent-gold)',
        'accent-crimson': 'var(--accent-crimson)',
        'accent-slate': 'var(--accent-slate)',
        'accent-light': 'var(--accent-light)',
        'brand-primary': '#4A3525',
        'brand-accent': '#E59A9A',
        'brand-light-bg': '#F8F5F2',
        'brand-light-surface': '#FFFFFF',
        'brand-light-text': '#1A1A1A',
        'brand-light-muted': '#6B6B6B',
        'brand-light-border': '#E5E5E5',
        'brand-dark-bg': '#1A1410',
        'brand-dark-surface': '#2C2C2E',
        'brand-dark-text': '#FFFFFF',
        'brand-dark-muted': '#A1A1A6',
        'brand-dark-border': '#3A3A3C',
      },
      borderRadius: {
        field: 12,
        button: 12,
        card: 16,
        sheet: 28,
      },
      fontFamily: {
        heading: ['serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        card: '0 10px 24px rgba(74, 53, 37, 0.12)',
        nav: '0 -8px 24px rgba(42, 28, 19, 0.18)',
        sheet: '0 -12px 32px rgba(42, 28, 19, 0.18)',
      },
    },
  },
  plugins: [],
}
